name: Code Scan


on:
 push:
   branches:
     - master


jobs:
 blacklock-scan:
   runs-on: ubuntu-latest
   container:
     image: blacklocksec/code-scanner:staging  # Directly use the scanner image


   env:
     SONAR_PROJECTKEY: "yC_nG9zYSqAA0vW5"
     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     SECURITY_SEVERITY_LEVELS: "low"


   steps:
     - name: Checkout Code
       uses: actions/checkout@v4


     - name: Run Blacklock Code Scanner
       run: /usr/local/bin/run.sh  # Adjust if the script location differs
